### ISSUE TITLE
tests for 1.4.0 use |> which isn't in 4.00 which is supported

### ISSUE THREAD

**Issue by dsheets** [rgrinberg/stringext#4]
this causes the tests to fail on 4.00.1

**Comment by rgrinberg** [comment]
My bad. Should be fixed in https://github.com/rgrinberg/stringext/commit/fc91beaab49da28a930d49c817fda59aac9cba9d

**Comment by seliopou** [comment]
The current travis-ci scripts perform a check for the installibility of dependencies using an `opam install my-package --deps-only`. This appears to be installing test dependencies as well, travis-ci builds will fail for 4.00 that have this library as a transitive dependency of the test dependencies. In my case, I'm in this situation because of alcotest.

Given the changes in master, this could be fixed through a patch release.
